export const unitConfig = [
    {
        id: 0,
        label: '台',
        code: '001',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 1,
        label: '座',
        code: '002',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 2,
        label: '辆',
        code: '003',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 3,
        label: '艘',
        code: '004',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 4,
        label: '架',
        code: '005',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 5,
        label: '套',
        code: '006',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 6,
        label: '个',
        code: '007',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 7,
        label: '只',
        code: '008',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 8,
        label: '头',
        code: '009',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 9,
        label: '张',
        code: '010',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 10,
        label: '件',
        code: '011',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 11,
        label: '支',
        code: '012',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 12,
        label: '枝',
        code: '013',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 13,
        label: '根',
        code: '014',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 14,
        label: '根',
        code: '015',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 15,
        label: '条',
        code: '016',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 16,
        label: '把',
        code: '017',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 17,
        label: '块',
        code: '018',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 18,
        label: '卷',
        code: '019',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 19,
        label: '副',
        code: '020',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 20,
        label: '片',
        code: '021',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 21,
        label: '组',
        code: '022',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 22,
        label: '份',
        code: '023',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 23,
        label: '幅',
        code: '024',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 24,
        label: '双',
        code: '025',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 25,
        label: '对',
        code: '026',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 26,
        label: '棵',
        code: '027',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 27,
        label: '株',
        code: '028',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 28,
        label: '井',
        code: '029',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 29,
        label: '米',
        code: '030',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 30,
        label: '盘',
        code: '031',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 31,
        label: '平方米',
        code: '032',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 32,
        label: '立方米',
        code: '033',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 33,
        label: '筒',
        code: '034',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 34,
        label: '千克',
        code: '035',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 35 ,
        label: '克',
        code: '036',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 36,
        label: '盆',
        code: '037',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 37,
        label: '万个',
        code: '038',
        changeRate: '10000',
        relatedCode: '007',
    },
    {
        id: 38,
        label: '具',
        code: '039',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 39,
        label: '百副',
        code: '040',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 40,
        label: '百支',
        code: '041',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 41,
        label: '百把',
        code: '042',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 42,
        label: '百个',
        code: '043',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 43,
        label: '百片',
        code: '044',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 44,
        label: '刀',
        code: '045',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 45,
        label: '疋',
        code: '046',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 46,
        label: '公担',
        code: '047',
        changeRate: '100',
        relatedCode: '035',
    },
    {
        id: 47,
        label: '扇',
        code: '048',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 48,
        label: '百枝',
        code: '049',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 49,
        label: '千只',
        code: '050',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 50,
        label: '千块',
        code: '051',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 51,
        label: '千盒',
        code: '052',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 52,
        label: '千枝',
        code: '053',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 53,
        label: '千个',
        code: '054',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 54,
        label: '亿支',
        code: '055',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 55,
        label: '亿个',
        code: '056',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 56,
        label: '万套',
        code: '057',
        changeRate: '10000',
        relatedCode: '006',
    },
    {
        id: 57,
        label: '千张',
        code: '058',
        changeRate: '1000',
        relatedCode: '010',
    },
    {
        id: 58,
        label: '万张',
        code: '059',
        changeRate: '10000',
        relatedCode: '010',
    },
    {
        id: 59,
        label: '千伏安',
        code: '060',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 60,
        label: '千瓦',
        code: '061',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 61,
        label: '千瓦时',
        code: '062',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 62,
        label: '千升',
        code: '063',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 63,
        label: '英尺',
        code: '067',
        changeRate: '.3048',
        relatedCode: '030',
    },
    {
        id: 64,
        label: '吨',
        code: '070',
        changeRate: '1000',
        relatedCode: '035',
    },
    {
        id: 65,
        label: '长吨',
        code: '071',
        changeRate: '1016',
        relatedCode: '035',
    },
    {
        id: 66,
        label: '短吨',
        code: '072',
        changeRate: '907.2',
        relatedCode: '035',
    },
    {
        id: 67,
        label: '司马担',
        code: '073',
        changeRate: '60.5',
        relatedCode: '035',
    },
    {
        id: 68,
        label: '司马斤',
        code: '074',
        changeRate: '.605',
        relatedCode: '035',
    },
    {
        id: 69,
        label: '斤',
        code: '075',
        changeRate: '.5',
        relatedCode: '035',
    },
    {
        id: 70,
        label: '磅',
        code: '076',
        changeRate: '.4536',
        relatedCode: '035',
    },
    {
        id: 71,
        label: '担',
        code: '077',
        changeRate: '100',
        relatedCode: '035',
    },
    {
        id: 72,
        label: '英担',
        code: '078',
        changeRate: '50.8024',
        relatedCode: '035',
    },
    {
        id: 73,
        label: '短担',
        code: '079',
        changeRate: '45.36',
        relatedCode: '035',
    },
    {
        id: 74,
        label: '两',
        code: '080',
        changeRate: '.05',
        relatedCode: '035',
    },
    {
        id: 75,
        label: '市担',
        code: '081',
        changeRate: '50',
        relatedCode: '035',
    },
    {
        id: 76,
        label: '盎司',
        code: '083',
        changeRate: '31.1',
        relatedCode: '036',
    },
    {
        id: 77,
        label: '克拉',
        code: '084',
        changeRate: '.2',
        relatedCode: '036',
    },
    {
        id: 78,
        label: '市尺',
        code: '085',
        changeRate: '.3333',
        relatedCode: '030',
    },
    {
        id: 79,
        label: '码',
        code: '086',
        changeRate: '.9144',
        relatedCode: '030',
    },
    {
        id: 80,
        label: '英寸',
        code: '088',
        changeRate: '.0245',
        relatedCode: '030',
    },
    {
        id: 81,
        label: '寸',
        code: '089',
        changeRate: '.0333',
        relatedCode: '030',
    },
    {
        id: 82,
        label: '升',
        code: '095',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 83,
        label: '毫升',
        code: '096',
        changeRate: '.001',
        relatedCode: '095',
    },
    {
        id: 84,
        label: '英加仑',
        code: '097',
        changeRate: '.0045',
        relatedCode: '033',
    },
    {
        id: 85,
        label: '美加仑',
        code: '098',
        changeRate: '.0037',
        relatedCode: '033',
    },
    {
        id: 86,
        label: '立方英尺',
        code: '099',
        changeRate: '.0283',
        relatedCode: '033',
    },
    {
        id: 87,
        label: '立方尺',
        code: '101',
        changeRate: '.037',
        relatedCode: '033',
    },
    {
        id: 88,
        label: '平方码',
        code: '110',
        changeRate: '.8361',
        relatedCode: '032',
    },
    {
        id: 89,
        label: '平方英尺',
        code: '111',
        changeRate: '.0929',
        relatedCode: '032',
    },
    {
        id: 90,
        label: '平方尺',
        code: '112',
        changeRate: '.111',
        relatedCode: '032',
    },
    {
        id: 91,
        label: '英制马力',
        code: '115',
        changeRate: '.7463',
        relatedCode: '061',
    },
    {
        id: 92,
        label: '公制马力',
        code: '116',
        changeRate: '.7353',
        relatedCode: '061',
    },
    {
        id: 93,
        label: '令',
        code: '118',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 94,
        label: '箱',
        code: '120',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 95,
        label: '批',
        code: '121',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 96,
        label: '罐',
        code: '122',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 97,
        label: '桶',
        code: '123',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 98,
        label: '扎',
        code: '124',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 99,
        label: '包',
        code: '125',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 100,
        label: '箩',
        code: '126',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 101,
        label: '打',
        code: '127',
        changeRate: '12',
        relatedCode: '011',
    },
    {
        id: 102,
        label: '筐',
        code: '128',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 103,
        label: '罗',
        code: '129',
        changeRate: '144',
        relatedCode: '007',
    },
    {
        id: 104,
        label: '匹',
        code: '130',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 105,
        label: '册',
        code: '131',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 106,
        label: '本',
        code: '132',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 107,
        label: '发',
        code: '133',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 108,
        label: '枚',
        code: '134',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 109,
        label: '捆',
        code: '135',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 110,
        label: '袋',
        code: '136',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 111,
        label: '粒',
        code: '139',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 112,
        label: '盒',
        code: '140',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 113,
        label: '合',
        code: '141',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 114,
        label: '瓶',
        code: '142',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 115,
        label: '千支',
        code: '143',
        changeRate: '1',
        relatedCode: '',
    },
    {
        id: 116,
        label: '万双',
        code: '144',
        changeRate: '10000',
        relatedCode: '025',
    },
    {
        id: 117,
        label: '万粒',
        code: '145',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 118,
        label: '千粒',
        code: '146',
        changeRate: '0',
        relatedCode: '',
    },
    {
        id: 119,
        label: '千米',
        code: '147',
        changeRate: '1000',
        relatedCode: '030',
    },
    {
        id: 120,
        label: '千英尺',
        code: '148',
        changeRate: '304.8',
        relatedCode: '030',
    },
    {
        id: 121,
        label: '百万贝可',
        code: '149',
        changeRate: '1',
        relatedCode: '063',
    },
    {
        id: 122,
        label: '部',
        code: '163',
        changeRate: '1',
        relatedCode: '001',
    },
    {
        id: 123,
        label: '亿株',
        code: '164',
        changeRate: '1',
        relatedCode: '071',
    },
]